name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  version: 
    required: true
    description: 'input description here'
    default: '1.6'
runs:
  using: 'node12'
  main: 'dist/index.js'
